TaskTwo/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TaskTwo.Models
{
    public class Order
    {
        public int Id {get;set;}
        public DateTime DatePurchase { get; set; }

        public int? UserId { get; set; }
        public User User { get; set; }

        public virtual ICollection<Product> Products { get; set; }
        public Order()
        {
            Products = new List<Product>();
        }

    }
}

TaskTwo/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TaskTwo.Models
{
    public class Product
    { 
        public int Id {get;set;}
        [Required(ErrorMessage = "Product name is required")]
        public string ProductName { get; set; }
        [Required(ErrorMessage = "Product price is required")]
        public int Price { get; set; }
        [Required(ErrorMessage = "Product describtion is required")]
        public string Describe { get; set; }
        public DateTime DateUpd { get; set; }

        public virtual ICollection<Order> Orders { get; set; }
        public Product()
        {
            Orders = new List<Order>();
            
        }
    }
}

TaskTwo/Models/PurchaseContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace TaskTwo.Models
{
    public class PurchaseContext : DbContext
    {
        public PurchaseContext() :
            base("DBConnection")
        { }

        public DbSet<Product> Products { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<User> Users { get; set; }
    }
}

TaskTwo/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TaskTwo.Models
{
    public class User
    {
        public int Id {get;set;}
        [Required(ErrorMessage = "User name is required")]
        public string Username {get;set;}
        [Required(ErrorMessage = "User surname is required")]
        public string Surname {get;set;}
        public DateTime DateRegister {get;set;}
        [Required(ErrorMessage = "User email is required")]
        public string Email { get; set; }

        
        public virtual ICollection<Order> Orders { get; set; }
        public User()
        {
            Orders = new List<Order>();
        }

}
}

TaskTwo/Controllers/CreatingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskTwo.Models;
using System.Net.Http;

namespace TaskTwo.Controllers
{
    public class CreatingController : Controller
    {
        private static readonly HttpClient client = new HttpClient();

        // GET: Creating
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateUser(User user)
        {
            user.DateRegister = DateTime.Now;

            using (PurchaseContext db = new PurchaseContext())
            {
                if (ModelState.IsValid)
                {
                    db.Users.Add(user);
                    db.SaveChanges();
                    ViewBag.Status = "Added user";
                    return View("Index");
                }
                else
                {
                    ViewBag.Status = "Error";
                    return View("Index");
                }
            }
        }

        [HttpPost]
        public ActionResult CreateProduct(Product product)
        {
            product.DateUpd = DateTime.Now;

            using (PurchaseContext db = new PurchaseContext())
            {
                if (ModelState.IsValid)
                {
                    db.Products.Add(product);
                    db.SaveChanges();
                    ViewBag.Status = "Added product";
                    return View("Index");
                }
                else
                {
                    ViewBag.Status = "Error";
                    return View("Index");
                }

            }
        }

        [HttpPost]
        public ActionResult CreateOrder()
        {
            Order order = new Order();

            using (PurchaseContext db = new PurchaseContext())
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        string username = Request["Email"];
                        string productname = Request["Productname"];

                        var user_order = db.Users.Where(t => t.Email == username).First();
                        var products = db.Products.Where(t => t.ProductName == productname).ToList();

                        order.DatePurchase = DateTime.Now;
                        order.User = user_order;
                        order.Products = products;

                        db.Orders.Add(order);
                        db.SaveChanges();

                        ViewBag.Status = "Order added";
                        return View("Index");
                    }
                    else
                    {
                        ViewBag.Status = "Error";
                        return View("Index");
                    }

                }
                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine(ex.Message);
                }
                return View("Error");
            }
        }
    }
}

TaskTwo/Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskTwo.Models;

namespace TaskTwo.Controllers
{
    public class DetailsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Users()
        {
            using (PurchaseContext db = new PurchaseContext())
            {
                var users = db.Users.ToList();
                return View(users);
            }
        }

        public ActionResult Products()
        {
            using (PurchaseContext db = new PurchaseContext())
            {
                var products = db.Products.ToList();
                return View(products);
            }
        }

        public ActionResult Orders()
        {
            using (PurchaseContext db = new PurchaseContext())
            {
                var orders = db.Orders.ToList();
                return View(orders);
            }
        }

        public ActionResult EditingUser()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UpdateUser(User user)
        {
            
            return View("Index");
        }
    }
}

TaskTwo/Controllers/EditingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TaskTwo.Controllers
{
    public class EditingController : Controller
    {
        // GET: Editing
        public ActionResult Index()
        {
            return View();
        }
    }
}

TaskTwo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskTwo.Models;

namespace TaskTwo.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

TaskTwo/Views/Creating/CreateOrder.cshtml
@model TaskTwo.Models.Order


@using (Html.BeginForm("CreateOrder", "Creating", FormMethod.Post))
{
    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />

        <div class="form-group">
            <label class="control-label col-md-2" for="Email">Email</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="Email" name="Email" type="text" value="" />
                <span class="field-validation-valid text-danger" data-valmsg-for="Email" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Productname">Product name</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="Productname" name="Productname" type="text" value="" />
                <span class="field-validation-valid text-danger" data-valmsg-for="Productname" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TaskTwo/Views/Creating/CreateProduct.cshtml
@model TaskTwo.Models.Product


@using (Html.BeginForm("CreateProduct", "Creating", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Describe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Describe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Describe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TaskTwo/Views/Creating/CreateUser.cshtml
@model TaskTwo.Models.User


@using (Html.BeginForm("CreateUser", "Creating", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TaskTwo/Views/Creating/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div class="row">
    <h2>Creating</h2>
    <hr />
    <div class="col-md-4">
        @Html.Partial("Createuser")
    </div>
    <div class="col-md-4">
        @Html.Partial("Createproduct")
    </div>
    <div class="col-md-4">
        @Html.Partial("Createorder")
    </div>
</div>
<h2>@ViewBag.Status</h2>

TaskTwo/Views/Details/EditingOrder.cshtml
@model TaskTwo.Models.Order

@{
    ViewBag.Title = "EditingOrder";
}

<h2>EditingOrder</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.DatePurchase, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatePurchase, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatePurchase, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TaskTwo/Views/Details/EditingProduct.cshtml
@model TaskTwo.Models.Product

@{
    ViewBag.Title = "EditingProduct";
}

<h2>EditingProduct</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Describe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Describe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Describe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateUpd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateUpd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateUpd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TaskTwo/Views/Details/EditingUser.cshtml
@model TaskTwo.Models.User

@{
    ViewBag.Title = "EditingUser";
}

<h2>EditingUser</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateRegister, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateRegister, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateRegister, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TaskTwo/Views/Details/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-sm-10">
        <h2>@Html.ActionLink("Users", "Users", "Details")</h2>
    </div>
</div>
<div class="row">
    <div class="col-sm-10">
        <h2>@Html.ActionLink("Products", "Products", "Details")</h2>
    </div>
</div>
<div class="row">
    <div class="col-sm-10">
        <h2>@Html.ActionLink("Details", "Orders", "Details")</h2>
    </div>
</div>

TaskTwo/Views/Details/Orders.cshtml
@model IEnumerable<TaskTwo.Models.Order>

@{
    ViewBag.Title = "Orders";
}

<h2>Orders</h2>

<p>
    @Html.ActionLink("Create New", "Index", "Creating")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.User.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DatePurchase)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.User.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DatePurchase)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

TaskTwo/Views/Details/Products.cshtml
@model IEnumerable<TaskTwo.Models.Product>

@{
    ViewBag.Title = "Products";
}

<h2>Products</h2>

<p>
    @Html.ActionLink("Create New", "Index", "Creating")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Describe)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateUpd)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProductName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Describe)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateUpd)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

TaskTwo/Views/Details/Users.cshtml
@model IEnumerable<TaskTwo.Models.User>

@{
    ViewBag.Title = "Users";
}

<h2>Users</h2>

<p>
    @Html.ActionLink("Create New", "Index", "Creating")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateRegister)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Surname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateRegister)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditingUser", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

TaskTwo/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<div class="row">
    <div class="col-sm-10">
        <h2>@Html.ActionLink("Creating", "Index", "Creating")</h2>
    </div>
</div>
<div class="row">
    <div class="col-sm-10">
        <h2>@Html.ActionLink("Details", "Index", "Details")</h2>
    </div>
</div>
</div>

TaskTwo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Creating", "Index", "Creating")</li>
                    <li>@Html.ActionLink("Details", "Index", "Details")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>